server:
  port: 8001

logging:
  level:
    org.mongodb.driver.cluster: ERROR
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: ${envspace}
  cache:
    jcache:
      config: classpath:/ehcache.xml
    type: ehcache
  datasource:
    dbcp2:
      initial-size: 10

sftp:
  username:
  password:
  host:
  port: 22
  priKeyFile:
  passphrase:
  directory:
  remoteFileName:

spring.mvc.static-path-pattern: /static/**
jasypt:
  encryptor:
    password: abcd
    algorithm: PBEWithSHA1AndDESede


spring.datasource.url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driverClassName: com.mysql.jdbc.Driver

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql: true
spring.thymeleaf.cache: false
spring.jpa.hibernate.ddl-auto: update













