#server:
#  port: 8080

logging:
  level:
    org.mongodb.driver.cluster: ERROR
  config: classpath:logback-spring.xml

spring:
  profiles:
    active: ${envspace}
  cache:
    jcache:
      config: classpath:/ehcache.xml
    type: ehcache
  datasource:
    dbcp2:
      initial-size: 10
#用于html文件中的 shiro:hasPermission语句
  thymeleaf:
     cache: false
     mode: LEGACYHTML5
sftp:
  username:
  password:
  host:
  port: 22
  priKeyFile:
  passphrase:
  directory:
  remoteFileName:

spring.mvc.static-path-pattern: /static/**
jasypt:
  encryptor:
    password: abcd
    algorithm: PBEWithSHA1AndDESede


spring.datasource.url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.driverClassName: com.mysql.jdbc.Driver

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql: true
spring.thymeleaf.cache: false
spring.jpa.hibernate.ddl-auto: update

spring.mail.host: smtp.qq.com
spring.mail.username: 1121008660@qq.com
spring.mail.password: akwyjkoppczxighd
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true















